name: gallery
description: A resource to help developers evaluate and use Flutter.

version: 2.4.0+020400

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_localized_locales: ^1.1.1
  cupertino_icons: ^0.1.3
  rally_assets: ^2.0.0
  meta:
  scoped_model:
  shrine_images: ^1.1.2
  flare_flutter: ^2.0.2
  url_launcher: ^5.1.6
  shared_preferences: ^0.5.4
  collection: ^1.14.0
  flutter_gallery_assets: ^0.2.1
  package_info: ^0.4.0
  google_fonts: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0

  flutter_gallery_additional_assets:
    git:
      url: https://github.com/pennzht/fluttergalleryadditionalassets.git
      ref: f4a7c99a56df62496bc057adb9e7b5b916e0f451

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  grinder: ^0.8.0
  intl_translation:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:
  assets:
    - packages/flutter_gallery_assets/assets/icons/settings/settings_light.flr
    - packages/flutter_gallery_assets/assets/icons/settings/settings_dark.flr
    - packages/flutter_gallery_assets/assets/studies/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/1.5x/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/2.0x/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/3.0x/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/4.0x/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/logo/1.5x/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/1.5x/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/logo/2.0x/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/2.0x/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/logo/3.0x/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/3.0x/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/logo/4.0x/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/4.0x/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/1.5x/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/2.0x/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/3.0x/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/4.0x/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/material/material.png
    - packages/flutter_gallery_assets/assets/icons/material/1.5x/material.png
    - packages/flutter_gallery_assets/assets/icons/material/2.0x/material.png
    - packages/flutter_gallery_assets/assets/icons/material/3.0x/material.png
    - packages/flutter_gallery_assets/assets/icons/material/4.0x/material.png
    - packages/flutter_gallery_assets/assets/icons/reference/1.5x/reference.png
    - packages/flutter_gallery_assets/assets/icons/reference/2.0x/reference.png
    - packages/flutter_gallery_assets/assets/icons/reference/reference.png
    - packages/flutter_gallery_assets/assets/icons/reference/3.0x/reference.png
    - packages/flutter_gallery_assets/assets/icons/reference/4.0x/reference.png
    - packages/flutter_gallery_assets/assets/demos/1.5x/bottom_navigation_background.png
    - packages/flutter_gallery_assets/assets/demos/2.0x/bottom_navigation_background.png
    - packages/flutter_gallery_assets/assets/demos/3.0x/bottom_navigation_background.png
    - packages/flutter_gallery_assets/assets/demos/4.0x/bottom_navigation_background.png
    - packages/flutter_gallery_assets/assets/demos/bottom_navigation_background.png
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoMono-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-ExtraBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-BoldItalic.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-SemiBold.ttf
    - packages/flutter_gallery_assets/crane/destinations/eat_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/eat_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_0.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/sleep_11.jpg
    - packages/flutter_gallery_assets/crane/logo/logo.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_army.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_bees.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_chart.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_fabrics.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_feminists.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_gas.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_healthcare.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_stocks.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_title.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_war.png
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/flutter_gallery_assets/splash_effects/splash_effect_1.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_2.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_3.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_4.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_5.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_6.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_7.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_8.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_9.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_10.gif
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf

