# Reads pubspec.yaml file and compare the version attribute to known tags.
# If a corresponding tag does not exist, it will be created.
#
# In turn, this triggers the three release workflows.
name: Create tag from pubspec
on:
  push:
#    branches:
#    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jacopocarlini/action-autotag@33f2200be533497d3b7a98a952a12a833f0d288f
        with:
          GITHUB_TOKEN: "${{ secrets.FLUTTERGITHUBBOT_TOKEN }}"
          ACTIONS_SETUP_DEBUG: true
          tag_prefix: "v"
