name: Publish MSIX to Microsoft Store

on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0

      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      - uses: microsoft/setup-msstore-cli@3b2ec9136230357ce9abc02b9d056626fb248d3f # v1
      
      # Instructions on obtaining these secrets can be found at https://github.com/marketplace/actions/windows-store-publish#obtaining-your-credentials
      - name: Configure MS CLI
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.SELLER_ID }}

      - name: Install dependencies
        run: flutter pub get
      
      - name: Create MSIX package
        run: msstore package
      
      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
